/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c478b58386e67faae974c92d3a0e4c1a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env {
		WORKER_FILES: KVNamespace;
		LOADER: WorkerLoader;
	}
}
interface Env extends Cloudflare.Env {}
